### ISSUE TITLE
RowVersion not increased on INSERT

### ISSUE THREAD

**Issue by heinrichti** [dorssel/dotnet-ef-sqlite-timestamp#48]
The RowVersion should be increased for newly created entities. Currently newly created entities get a zero row version. RowVersion is often used to synchronize changes between databases, and if we only get zeros we cannot determine if the entity is new or not.

**Comment by heinrichti** [comment]
In SQL Server the RowVersion will update on every _insert_ and update (as stated here: https://learn.microsoft.com/en-us/sql/t-sql/data-types/rowversion-transact-sql). That means that newly created records will have a row version bigger than all row versions that already exist in the table.

> When you read from the database, then 0 means it is a newly inserted record that was never updated after insertion. Your change only offsets everything by 1.

Not exactly, with my change the first (unchanged) record will have the rowversion 1, the second 2 and so on. Meaning we clearly know that the change to the second record is newer than the first record.

In my use case I have two databases, Db1 and Db2. Periodically I need to fetch data from Db1 and store it in Db2. As we are talking about a lot of data and the databases are not in the same location, so we want to query only the data that has changed since the last query. So if I want to get all the rows that changed (as in they are new or were updated), let's say since moment A, then I can remember the max rowversion of moment A and can query everything with a rowversion > the remembered rowversion.

With my change this will include all newly created rows, as their rowversion is higher than the rowversion of existing rows that have not changed, so this will mimic the behavior of SQL Server more closely. Before my change this would omit all newly created rows, as they will always have the rowversion 0, which will always be smaller than the remembered rowversion from moment A.

As a side note: If I understand the documentation correctly, in SQL Server the rowversion will not be increased for each table (as we do here) but within each database. For my use-cases we can neglect this difference.

I hope this makes it clearer what I am trying to achieve, and thanks for considering the change!

**Comment by dorssel** [comment]
> With my change this will include all newly created rows, as their rowversion is higher than the rowversion of existing rows that have not changed

That's not true. Every row starts at its own beginning. There is no relation between the row versions of different rows. At least not for SQLite. I know that for MSSQL Server, it used to be a timestamp (100 ns resolution), and nowadays it is a global counter. So it just happens to be monotonically incrementing across rows (and even across tables). But that is not guaranteed by the specs, nor is it a supported use case (even though it works in practice). The row version field is "opaque" to the application, and its only supported use case is concurrency detection.

> this will mimic the behavior of SQL Server more closely

It won't, and unfortunately it can't. SQLite does not have an atomic global counter. Even if you would implement it with a separate table just for this counter, there is no way of synchronizing its use between threads. Transactions won't help there either.

So, I have to disappoint you, but your trick which just happens to work for MSSQL Server does not work for SQLite.
